---
title: "git_01"
author: "iboni archie"
date: "summer 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
How doth the little crocodile  
Improve his shining tail , And pour the waters of the Nile  
On every golden scale!  
How cheerfully he seems to grin ,  

## Second Verse
Nature’s first green is gold,  
Her hardest hue to hold.  
Her early leaf’s a flower;  
But only so an hour.  
Then leaf subsides to leaf.  

## Third Verse
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright—  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done—  
“It’s very rude of him,” she said,  
“To come and spoil the fun!”  

## Last Verse
It is the color of light,  
The shape of sound high in the evergreens  
It lies suspended in hills,  
A blue line in a red sky.  
I am looking at sound.  
I am hearing the brightness  
Of high bluffs and almond trees  
I am tasting the wilderness  
of lakes, rivers, and streams  
Caught in an angle of song.  
I am remembering water  
That glows in the dawn  
The motion tumbled in earth  
Life hidden in mounds.  
I am dancing a bright beam of light  
I am remembering love.  
